management:
  security:
    enabled: false
  cloudfoundry:
    skip-ssl-validation: true
  info:
    git:
      enabled: true

security:
  basic:
    enabled: false

greeting: Hello World
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop