greeting: Welcome to the Movie Catalog!
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
 
endpoints:
  health:
    sensitive: false
    
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop