management:
  security:
    enabled: false
security:
  basic:
    enabled: false
spring:
  application:
    name: springbox-catalog
  profiles:
    active: spanish 
  jpa:
    hibernate:
      ddl-auto: create-drop
greeting: Hello World

---
spring:
  profiles: spanish
greeting: Hola